/**
 * CNXT-Connector
 * The CNXT-Connector is developed by Rodenstock GmbH to integrate data from measurement devices such as DNEye<sup>®</sup> Scanner, Rodenstock Fundus Scanner, and ImpressionIST<sup>®</sup> into 3rd party applications as well as into several applications of Rodenstock such as WinFit, Rodenstock Consulting etc. If you have any feedback then please feel free to contact us via email. Copyright © Rodenstock GmbH 2020
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cnxt@rodenstock.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.2.3.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PatientsResponse.h
 *
 * Represents a patients response
 */

#ifndef COM_RODENSTOCK_CNXT_CONNECTOR_CLIENT_MODEL_PatientsResponse_H_
#define COM_RODENSTOCK_CNXT_CONNECTOR_CLIENT_MODEL_PatientsResponse_H_


#include "../ModelBase.h"

#include "PageInfo.h"
#include "PaginationLink.h"
#include <vector>
#include "PatientResponse.h"

namespace com {
namespace rodenstock {
namespace cnxt {
namespace connector {
namespace client {
namespace model {


/// <summary>
/// Represents a patients response
/// </summary>
class  PatientsResponse
    : public ModelBase
{
public:
    PatientsResponse();
    virtual ~PatientsResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// PatientsResponse members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<PatientResponse>>& getPatients();
    bool patientsIsSet() const;
    void unsetPatients();

    void setPatients(const std::vector<std::shared_ptr<PatientResponse>>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<PaginationLink> getLinks() const;
    bool linksIsSet() const;
    void unset_links();

    void setLinks(const std::shared_ptr<PaginationLink>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<PageInfo> getPageInfo() const;
    bool pageInfoIsSet() const;
    void unsetPageInfo();

    void setPageInfo(const std::shared_ptr<PageInfo>& value);


protected:
    std::vector<std::shared_ptr<PatientResponse>> m_Patients;
    bool m_PatientsIsSet;
    std::shared_ptr<PaginationLink> m__links;
    bool m__linksIsSet;
    std::shared_ptr<PageInfo> m_PageInfo;
    bool m_PageInfoIsSet;
};


}
}
}
}
}
}

#endif /* COM_RODENSTOCK_CNXT_CONNECTOR_CLIENT_MODEL_PatientsResponse_H_ */
