/**
 * CNXT-Connector
 * The CNXT-Connector is developed by Rodenstock GmbH to integrate data from measurement devices such as DNEye<sup>®</sup> Scanner, Rodenstock Fundus Scanner, and ImpressionIST<sup>®</sup> into 3rd party applications as well as into several applications of Rodenstock such as WinFit, Rodenstock Consulting etc. If you have any feedback then please feel free to contact us via email. Copyright © Rodenstock GmbH 2020
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cnxt@rodenstock.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.2.3.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 /*
  * PatientLink_session.h
  *
  *
  */

#ifndef COM_RODENSTOCK_CNXT_CONNECTOR_CLIENT_MODEL_PatientLink_session_H_
#define COM_RODENSTOCK_CNXT_CONNECTOR_CLIENT_MODEL_PatientLink_session_H_

#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
	namespace rodenstock {
		namespace cnxt {
			namespace connector {
				namespace client {
					namespace model {
						/// <summary>
						///
						/// </summary>
						class  PatientLink_session
							: public ModelBase
						{
						public:
							PatientLink_session();
							virtual ~PatientLink_session();

							/////////////////////////////////////////////
							/// ModelBase overrides

							void validate() override;

							web::json::value toJson() const override;
							void fromJson(const web::json::value& json) override;

							void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
							void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

							/////////////////////////////////////////////
							/// PatientLink_session members

							/// <summary>
							/// The URI of the session being expressed with a self link.
							/// </summary>
							utility::string_t getHref() const;
							bool hrefIsSet() const;
							void unsetHref();

							void setHref(const utility::string_t& value);

						protected:
							utility::string_t m_Href;
							bool m_HrefIsSet;
						};
					}
				}
			}
		}
	}
}

#endif /* COM_RODENSTOCK_CNXT_CONNECTOR_CLIENT_MODEL_PatientLink_session_H_ */
